chore: Ci implementation
looker-open-source/viz-histogram-marketplace pull request #20
Opened 2024-05-22 22:50 UTC by elivillalejos

Hi! Patching from [this PR ](https://github.com/looker-open-source/viz-histogram-marketplace/pull/18)so I can fix the ci-workflow from Github as logs are no longer available in that one.

2024-05-23 00:18 UTC, yesudeep requested changes

2024-05-23 00:18 UTC, yesudeep commented on .github/ci-build.yml
> +    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-ci-build.yml@main
Let's ensure there is a blank line at the EOF throughout the PR.
Not having that prevents certain tools from working currectly on unix

2024-05-24 16:58 UTC, elivillalejos commented on .github/ci-build.yml
> +    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-ci-build.yml@main
Addressed this in the last commit, thank you.

2024-06-01 18:32 UTC, yesudeep requested changes

2024-06-01 18:32 UTC, yesudeep commented on webpack.config.js
> +module.exports = webpackConfig;
nit: please ensure the file ends with a EOL character and doesn't have additional trailing newlines.

2024-06-01 18:32 UTC, yesudeep commented on .github/ci-build.yml
> +
nit: please ensure the file ends with a EOL character and doesn't have additional trailing newlines.

2024-07-04 18:45 UTC, yesudeep approved these changes

2024-07-04 18:45 UTC, merged